# Generated by Django 5.2 on 2025-04-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackit', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='priority',
            field=models.CharField(blank=True, choices=[('C', 'Critical'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1),
        ),
    ]
