# Generated by Django 5.2 on 2025-05-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackit', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.ManyToManyField(blank=True, to='trackit.document'),
        ),
    ]
