# Generated by Django 5.2 on 2025-05-01 21:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackit', '0006_application_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), default=['company', 'idk'], size=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracker',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
