# Generated by Django 5.2 on 2025-05-03 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackit', '0007_tracker_fields_alter_tracker_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), default=list, size=50),
        ),
    ]
