# Generated by Django 5.2 on 2025-05-03 15:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackit', '0009_alter_tracker_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=50),
        ),
    ]
