# Generated by Django 5.2 on 2025-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackit', '0010_alter_tracker_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
